#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

case "${1:-}" in
  get_throttled)
    printf '%s\n' 'throttled=0x0'
    ;;
  pmic_read_adc)
    if [[ "${2:-}" != 'EXT5V_V' ]]; then
      printf '%s\n' 'fixture pmic_read_adc requires EXT5V_V' >&2
      exit 2
    fi
    printf '%s\n' 'volt=5.1234V'
    ;;
  *)
    printf 'Unsupported firmware command: %s\n' "${1:-}" >&2
    exit 2
    ;;
esac
